# Generated by Django 5.2.2 on 2025-06-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
