# Generated by Django 5.2.2 on 2025-07-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_quiz_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='type',
            field=models.CharField(default='multiple-choice', max_length=50),
        ),
    ]
