# Generated by Django 5.2.2 on 2025-07-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_quizquestion_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='QuizChoice',
        ),
    ]
