# Generated by Django 5.2.2 on 2025-07-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_choice_quizchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
