# Generated by Django 5.2.2
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0018_assignment_published_quiz_published')]

    operations = [
        migrations.AddField(model_name='assignment', name='description', field=models.TextField(blank=True)),
        migrations.AddField(model_name='assignment', name='submission_text', field=models.TextField(blank=True)),
        migrations.AddField(model_name='assignment', name='submitted_at', field=models.DateTimeField(blank=True, null=True)),
    ]
