# Generated by Django 5.2.2 on 2026-08-11 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_secondary_english_resources(apps, schema_editor):
    LearningResource = apps.get_model('users', 'LearningResource')
    source = 'Secondary English 4 Student’s Book (South Sudan, 2018)'
    resources = [
        {
            'title': 'Unit 1: Gender Issues', 'resource_type': 'reading', 'source_reference': 'Unit 1, pp. 1–37',
            'description': 'Reading and discussion material on gender equality, discrimination, equity and rights.',
            'content': 'Learning focus: analyse gender equality and discrimination; build topic vocabulary; discuss, debate and research gender equity. Suggested assessment: write a short evidence-based advocacy message for gender equality.',
        },
        {
            'title': 'Unit 2: Transport', 'resource_type': 'activity', 'source_reference': 'Unit 2, pp. 38–53',
            'description': 'Reading, vocabulary and research activities on transport, the economy and local transport challenges.',
            'content': 'Learning focus: explain how transport supports communities and the economy; identify transport challenges in South Sudan; conduct a short local research task. Suggested assessment: compare two transport solutions in a structured paragraph.',
        },
        {
            'title': 'Unit 3: Corruption', 'resource_type': 'reading', 'source_reference': 'Unit 3, pp. 54–72',
            'description': 'Society, economy, vocabulary, listening and language-practice resources about corruption.',
            'content': 'Learning focus: explain the effects of corruption on society and the economy; compare impacts; use anti-corruption vocabulary accurately. Suggested assessment: create a cause-and-effect map and support it with examples.',
        },
        {
            'title': 'Unit 4: Communication Technology', 'resource_type': 'activity', 'source_reference': 'Unit 4, pp. 73–92',
            'description': 'Reading, listening, research and debate resources about communication technology and its social impact.',
            'content': 'Learning focus: assess the benefits and limitations of communication technology; build digital-communication vocabulary; present a researched view. Suggested assessment: prepare a balanced debate statement using evidence.',
        },
        {
            'title': 'Unit 5: Culture and Society', 'resource_type': 'reading', 'source_reference': 'Unit 5, pp. 93–113',
            'description': 'Drama, reading, listening and research activities on culture, society and cultural preservation.',
            'content': 'Learning focus: connect culture with social and economic life; explore cultural change; research ways to preserve cultural heritage. Suggested assessment: design a one-page cultural preservation proposal.',
        },
        {
            'title': 'Unit 6: Democracy', 'resource_type': 'assessment', 'source_reference': 'Unit 6, pp. 114–135',
            'description': 'Readings, discussion, research and writing prompts on democracy, leadership and political systems.',
            'content': 'Learning focus: describe how democracy works; compare political systems; research the origins of democracy; write a reasoned response. Suggested assessment: use a claim, evidence and explanation structure to answer a democracy question.',
        },
        {
            'title': 'Unit 7: Justice', 'resource_type': 'activity', 'source_reference': 'Unit 7, pp. 136–140',
            'description': 'Reading, vocabulary, listening and research activities on justice and justice institutions.',
            'content': 'Learning focus: explain justice and the roles of justice institutions; use legal and civic vocabulary; research a local justice issue. Suggested assessment: create a short scenario and identify a fair response.',
        },
    ]
    for resource in resources:
        LearningResource.objects.get_or_create(
            title=resource['title'], source=source,
            defaults={**resource, 'subject_area': 'English', 'is_published': True},
        )


def remove_secondary_english_resources(apps, schema_editor):
    LearningResource = apps.get_model('users', 'LearningResource')
    LearningResource.objects.filter(source='Secondary English 4 Student’s Book (South Sudan, 2018)').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_assignment_quiz_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject_area', models.CharField(blank=True, max_length=100)),
                ('resource_type', models.CharField(choices=[('reading', 'Reading'), ('activity', 'Activity'), ('video', 'Video'), ('worksheet', 'Worksheet'), ('assessment', 'Assessment prompt')], default='reading', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('source_reference', models.CharField(blank=True, max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['subject_area', 'title'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='quizzes', to='users.learningresource'),
        ),
        migrations.AddField(
            model_name='subject',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='courses', to='users.learningresource'),
        ),
        migrations.RunPython(seed_secondary_english_resources, remove_secondary_english_resources),
    ]
