from django.db import migrations


def expand_unit_content(apps, schema_editor):
    LearningResource = apps.get_model('users', 'LearningResource')
    content = {
        'Secondary English 4 Student’s Book (South Sudan, 2018)': {
            'Unit 1: Gender Issues': 'Unit lesson guide\nFocus: gender equality, discrimination and social responsibility.\nTopics: gender roles; equality and equity; rights; stereotypes; advocacy vocabulary.\nLearning activities: close reading, class discussion, debate, research and persuasive writing.\nCheck for understanding: explain an inequality, support a viewpoint with evidence, and write a respectful advocacy message.',
            'Unit 2: Transport': 'Unit lesson guide\nFocus: transport and its contribution to communities and the economy.\nTopics: transport systems, economic links, local challenges, research vocabulary and language practice.\nLearning activities: read an informational text, build a topic word bank, discuss local transport, conduct short research.\nCheck for understanding: compare transport solutions and justify one recommendation in a structured paragraph.',
            'Unit 3: Corruption': 'Unit lesson guide\nFocus: corruption, its consequences and ethical civic action.\nTopics: effects on society and the economy, institutions, vocabulary, anti-corruption action, poetry and speech.\nLearning activities: cause-and-effect mapping, paired comparison, discussion and short speech preparation.\nCheck for understanding: explain two impacts of corruption and propose a realistic preventative action.',
            'Unit 4: Communication Technology': 'Unit lesson guide\nFocus: communication technology and its effects on society.\nTopics: technology in daily life, digital vocabulary, expert listening, research, reading and debate.\nLearning activities: analyse a text, gather evidence, debate benefits and risks, practise language choices.\nCheck for understanding: deliver a balanced claim with evidence about a technology issue.',
            'Unit 5: Culture and Society': 'Unit lesson guide\nFocus: culture, social change and cultural preservation.\nTopics: drama, cultural identity, cultural and economic life, vocabulary, community listening and research.\nLearning activities: perform or read a play, discuss cultural change, interview or research, create a preservation plan.\nCheck for understanding: explain how a cultural practice shapes society and propose a preservation action.',
            'Unit 6: Democracy': 'Unit lesson guide\nFocus: democracy, leadership and participation.\nTopics: democratic systems, political systems, civic discussion, community voices, research, fiction and writing.\nLearning activities: compare systems, hold a guided discussion, research an origin or example, write an evidence-based response.\nCheck for understanding: make a claim about democracy and support it with accurate examples.',
            'Unit 7: Justice': 'Unit lesson guide\nFocus: justice and the institutions that support it.\nTopics: justice in South Sudan, civic vocabulary, community perspectives, institutions, media and language practice.\nLearning activities: reading, vocabulary building, listening, research and scenario analysis.\nCheck for understanding: identify an institution relevant to a justice scenario and explain a fair response.',
        },
        'Chemistry Student’s Book 4 (South Sudan)': {
            'Unit 1: Ions and Gases': 'Unit lesson guide\nFocus: qualitative analysis of ions and gases.\nTopics: cation tests with sodium hydroxide and ammonia; anion tests; gas tests; observations and safety.\nLearning activities: plan a practical test, record a results table, compare precipitates and interpret observations.\nCheck for understanding: design a safe method to distinguish unknown samples and state the expected result.',
            'Unit 2: Energy Changes in Chemical Reactions': 'Unit lesson guide\nFocus: energy changes during chemical reactions.\nTopics: heat of reaction, exothermic and endothermic change, energy profiles, bond formation and breaking, enthalpy and activation energy.\nLearning activities: temperature-change investigation, diagram interpretation and bond-energy calculation practice.\nCheck for understanding: classify a reaction from evidence and explain its energy profile.',
            'Unit 3: Kinetics, Equilibrium and Electrochemistry': 'Unit lesson guide\nFocus: rates, reversible reactions and electricity in chemical change.\nTopics: collision theory, rate measurements, rate factors, equilibrium, electrolysis and the roles of water and electricity.\nLearning activities: fair-test planning, graph discussion, equilibrium modelling and electrolysis explanation.\nCheck for understanding: predict how a changed condition affects rate or equilibrium and justify it.',
            'Unit 4: Metals, Ores and Extraction': 'Unit lesson guide\nFocus: common metal ores, extraction and properties.\nTopics: sodium, aluminium, copper, iron, zinc, chromium, reactivity and metal properties.\nLearning activities: compare extraction methods, link reactivity to process, analyse use cases.\nCheck for understanding: recommend an extraction method for a named metal and explain the choice.',
            'Unit 5: Analytical Techniques and Structure': 'Unit lesson guide\nFocus: techniques used to identify substances and structures.\nTopics: chromatography, infrared, nuclear magnetic resonance, ultraviolet and mass spectroscopy.\nLearning activities: compare evidence types, match instruments to questions and interpret simple results.\nCheck for understanding: select an analytical technique for a sample and defend the decision.',
            'Unit 6: Organic Chemistry': 'Unit lesson guide\nFocus: carbon compounds and their applications.\nTopics: hydrocarbons, alkanes, alkenes, alkynes, alcohols, acids, detergents, polymers, fibres, aldehydes and ketones.\nLearning activities: classify compounds, draw comparisons and connect structure to everyday uses.\nCheck for understanding: identify a homologous series and explain one property or use from structure.',
            'Unit 7: Nuclear Chemistry': 'Unit lesson guide\nFocus: radioactivity and nuclear processes.\nTopics: radiation types, fission, fusion, decay rate and medical applications.\nLearning activities: compare radiation properties, model half-life and evaluate a health application with safety in mind.\nCheck for understanding: distinguish fission from fusion and explain an application of radioactivity.',
        },
        'Secondary Biology 4 Student Textbook (South Sudan)': {
            'Unit 1: Photosynthesis and Respiration': 'Unit lesson guide\nFocus: biochemical processes that supply and release energy.\nTopics: chlorophyll, light, carbon dioxide, limiting factors, leaf adaptation, respiration and gaseous exchange.\nLearning activities: starch-test planning, leaf-structure analysis and comparison of photosynthesis with respiration.\nCheck for understanding: write and explain the equations for both processes and identify a limiting factor.',
            'Unit 2: Reproduction and Growth': 'Unit lesson guide\nFocus: reproduction, development and cell division in plants and animals.\nTopics: asexual and sexual reproduction, flowers, pollination, seeds, human reproduction, pregnancy, chromosomes, mitosis, meiosis and growth.\nLearning activities: sequence diagrams, compare processes, model inheritance-linked cell division.\nCheck for understanding: explain why meiosis and mitosis have different roles.',
            'Unit 3: Co-ordination in Plants and Animals': 'Unit lesson guide\nFocus: how organisms detect and respond to change.\nTopics: plant responses, auxin, nervous system structure, neurones, reflexes and endocrine coordination.\nLearning activities: reflex-arc labelling, stimulus-response scenarios and comparison of fast and slow coordination.\nCheck for understanding: trace a response from stimulus to effector.',
            'Unit 4: Homeostasis': 'Unit lesson guide\nFocus: maintaining stable internal conditions.\nTopics: definition of homeostasis, endocrine control and osmoregulation.\nLearning activities: analyse body-balance scenarios, create feedback-flow diagrams and compare plant and animal responses.\nCheck for understanding: explain how an organism responds when water level or temperature changes.',
            'Unit 5: Genetics and Inheritance': 'Unit lesson guide\nFocus: inheritance, variation and genetic change.\nTopics: genetic terminology, monohybrid crosses, dominance patterns, sex linkage, variation, mutation, evolution and genetic engineering.\nLearning activities: solve inheritance problems, build vocabulary, compare sources of variation and discuss applications.\nCheck for understanding: use a genetic cross to predict outcomes and explain the result.',
            'Unit 6: Adaptation and Evolution': 'Unit lesson guide\nFocus: evolutionary explanation and adaptation.\nTopics: origins of life, natural selection, convergent and divergent evolution, evolutionary trees and adaptation.\nLearning activities: compare organisms, interpret selection scenarios and create claim-evidence-reasoning explanations.\nCheck for understanding: explain how natural selection changes a population over generations.',
            'Unit 7: Support and Movement': 'Unit lesson guide\nFocus: structures that support movement in plants and animals.\nTopics: support in plants, movement in animals and the mammalian skeleton.\nLearning activities: compare support systems, label skeletal structures and relate form to function.\nCheck for understanding: describe how one structure enables movement or support.',
        },
        'Secondary Physics 4 Student Textbook (South Sudan)': {
            'Unit 1: Periodic Motion': 'Unit lesson guide\nFocus: circular motion and simple harmonic motion.\nTopics: angular displacement and velocity, centripetal force, vertical circles, oscillation, period, frequency, energy and damping.\nLearning activities: practical circular-motion investigations, pendulum work and formula application.\nCheck for understanding: calculate a periodic quantity and explain the motion using force or energy.',
            'Unit 2: Newton’s Law of Gravitation': 'Unit lesson guide\nFocus: gravitational interaction and orbital motion.\nTopics: universal gravitation, Kepler’s laws and practical applications.\nLearning activities: model an orbit, use proportional reasoning and apply the gravitational law to scenarios.\nCheck for understanding: explain how gravity supports an orbital path.',
            'Unit 3: Wave Behaviour': 'Unit lesson guide\nFocus: reflection, refraction, interference and diffraction.\nTopics: ripple tanks, wave fronts, pulses, stationary waves, air columns, beats, dual nature of light and polarisation.\nLearning activities: draw wave diagrams, use a ripple model and compare wave behaviours.\nCheck for understanding: predict a wave result at a boundary or gap and explain why.',
            'Unit 4: Electric Fields and Capacitance': 'Unit lesson guide\nFocus: electric fields, potential and stored charge.\nTopics: field patterns, field strength, electric potential, charge distribution, capacitors, charging, discharging and electrostatic applications.\nLearning activities: annotate field diagrams, explore capacitor variables and interpret charge-flow changes.\nCheck for understanding: explain how a capacitor stores and releases charge.',
            'Unit 5: Magnetic Fields and Electromagnetic Induction': 'Unit lesson guide\nFocus: magnetism, motors, induction and electrical generation.\nTopics: current-carrying conductors, solenoids, coils, motor effect, Biot-Savart ideas, induction, transformers and generators.\nLearning activities: field-pattern investigation, device diagrams and transformer calculations.\nCheck for understanding: explain an energy transfer in a motor, generator or transformer.',
            'Unit 6: Cathode Ray Tube': 'Unit lesson guide\nFocus: cathode rays and the cathode ray oscilloscope.\nTopics: production and properties of cathode rays, CRO components and applications.\nLearning activities: label apparatus, investigate beam behaviour and interpret a simple display.\nCheck for understanding: describe one use of a CRO and the evidence it provides.',
            'Unit 7: Radioactivity and Nuclear Energy': 'Unit lesson guide\nFocus: radioactive decay, nuclear change and safe application.\nTopics: models of decay, half-life, radiation properties and detectors, natural and artificial radioactivity, fission, fusion and applications.\nLearning activities: half-life modelling, radiation comparison and application evaluation.\nCheck for understanding: interpret a decay scenario and compare fission with fusion.',
        },
    }
    for source, units in content.items():
        for title, lesson_content in units.items():
            LearningResource.objects.filter(source=source, title=title).update(content=lesson_content)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0023_seed_science_resources'),
    ]

    operations = [migrations.RunPython(expand_unit_content, migrations.RunPython.noop)]
