# Generated by Django 5.2.2 on 2026-08-11 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_expand_unit_repository_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='answer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.quizchoice'),
        ),
    ]
